name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      # Checkout dev-repo
      - name: Checkout Development Repository
        uses: actions/checkout@v3

      # Install Ruby and Jekyll dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      # Build Jekyll site
      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git clone https://github.com/hshah-mitre/dev-repo.git gh-pages
          cd gh-pages
          git checkout gh-pages || git checkout -b gh-pages
          rm -rf *
          cp -r ../_site/* .
          git add .
          git commit -m "Deploy Jekyll site to GitHub Pages"
          git push origin gh-pages

  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      # Checkout dev-repo
      - name: Checkout Development Repository
        uses: actions/checkout@v3

      # Install Ruby and Jekyll dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      # Build Jekyll site
      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build

      # Deploy to Production Repository
      - name: Deploy to Production Repository
        run: |
          git clone https://hshah-mitre:${{ secrets.PROD_REPO_PAT }}@github.com/hshah-mitre/prod-repo.git prod-repo
          cd prod-repo
          git pull origin main
          rsync -av --exclude='.git' ./_site/ prod-repo/
          cd prod-repo
          git add .
          git commit -m "Deploy Jekyll site to Production Repository"
          git push origin main
