name: Deploy to Production and GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the dev-repo
      - name: Checkout Development Repository
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Install Ruby and Jekyll dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Specify the Ruby version compatible with Jekyll
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the Jekyll site in dev-repo
      - name: Build Jekyll Site in Development Repository
        run: |
          bundle exec jekyll build

      # Step 5: Clone the prod-repo
      - name: Clone Production Repository
        run: |
          git clone https://hshah-mitre:${{ secrets.PROD_REPO_PAT }}@github.com/hshah-mitre/prod-repo.git prod-repo
          cd prod-repo
          git pull origin main

      # Step 6: Copy built Jekyll site from dev-repo to prod-repo
      - name: Copy Built Site to Production Repository
        run: |
          rsync -av --exclude='.git' ./_site/ prod-repo/

      # Step 7: Commit and Push Changes to prod-repo
      - name: Commit and Push Changes
        run: |
          cd prod-repo
          git add .
          git commit -m "Deploy Jekyll site from dev-repo to prod-repo"
          git push origin main

  deploy-pages:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the dev-repo
      - name: Checkout Development Repository
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Install Ruby and Jekyll dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Specify the Ruby version compatible with Jekyll
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the Jekyll site in dev-repo
      - name: Build Jekyll Site in Development Repository
        run: |
          bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          # Clone the repository
          git clone https://github.com/hshah-mitre/dev-repo.git gh-pages
          cd gh-pages

          # Create gh-pages branch if it doesn't exist
          if ! git rev-parse --verify gh-pages; then
            git checkout --orphan gh-pages
          else
            git checkout gh-pages
          fi

          # Remove old files and copy new ones
          rm -rf *
          cp -r ../_site/* .

          # Commit and push changes to gh-pages branch
          git add .
          git commit -m "Deploy Jekyll site to GitHub Pages"
          git push origin gh-pages
